// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwouzostxhbqhkwenwtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3b3V6b3N0eGhicWhrd2Vud3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzA4ODYsImV4cCI6MjA3MDI0Njg4Nn0.QySMmjzsTqCjf5kFlim9b6fK1tY-v-Bd7tqSJebnRAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});